// Code generated by "gonum -types=ParameterTypeEnum"; DO NOT EDIT.

package t8

import "encoding/json"
import "errors"
import "fmt"

type parameterTypeInstanceJsonDescriptionModel struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

var parameterTypeInstance = ParameterTypeEnum{
	String: "string",
	List:   "list",
	Option: "option",
}

// ParameterType is the enum that instances should be created from
type ParameterType struct {
	name        string
	value       string
	description string
}

// Enum instances
var String = ParameterType{name: "string", value: "String", description: ""}
var List = ParameterType{name: "list", value: "List", description: ""}
var Option = ParameterType{name: "option", value: "Option", description: ""}

// NewParameterType generates a new ParameterType from the given display value (name)
func NewParameterType(value string) (ParameterType, error) {
	switch value {
	case "string":
		return String, nil
	case "list":
		return List, nil
	case "option":
		return Option, nil
	default:
		return ParameterType{}, errors.New(
			fmt.Sprintf("'%s' is not a valid value for type", value))
	}
}

// Name returns the enum display value
func (g ParameterType) Name() string {
	switch g {
	case String:
		return String.name
	case List:
		return List.name
	case Option:
		return Option.name
	default:
		panic("Could not map enum")
	}
}

// String returns the enum display value and is an alias of Name to implement the Stringer interface
func (g ParameterType) String() string {
	return g.Name()
}

// Error returns the enum name and implements the Error interface
func (g ParameterType) Error() string {
	return g.Name()
}

// Description returns the enum description if present. If no description is defined an empty string is returned
func (g ParameterType) Description() string {
	switch g {
	case String:
		return ""
	case List:
		return ""
	case Option:
		return ""
	default:
		panic("Could not map enum description")
	}
}

// ParameterTypeNames returns the displays values of all enum instances as a slice
func ParameterTypeNames() []string {
	return []string{
		"string",
		"list",
		"option",
	}
}

// ParameterTypeValues returns all enum instances as a slice
func ParameterTypeValues() []ParameterType {
	return []ParameterType{
		String,
		List,
		Option,
	}
}

// MarshalJSON provides json serialization support by implementing the Marshaler interface
func (g ParameterType) MarshalJSON() ([]byte, error) {
	if g.Description() != "" {
		m := parameterTypeInstanceJsonDescriptionModel{
			Name:        g.Name(),
			Description: g.Description(),
		}
		return json.Marshal(m)
	}
	return json.Marshal(g.Name())
}

// UnmarshalJSON provides json deserialization support by implementing the Unmarshaler interface
func (g *ParameterType) UnmarshalJSON(b []byte) error {
	var v string
	err := json.Unmarshal(b, &v)
	if err != nil {
		return err
	}

	instance, createErr := NewParameterType(v)
	if createErr != nil {
		return createErr
	}

	g.name = instance.name
	g.value = instance.value

	return nil
}
